import json

from bedrock.client import BedrockClient
from botocore.exceptions import ClientError

from typing import Optional

import logging

from dotenv import load_dotenv

load_dotenv()

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class BedrockAnthropicChatCompletions(BedrockClient):
    """ A class to generate chat completions using Bedrock's Anthropic text models"""
    # Reference: https://docs.aws.amazon.com/bedrock/latest/userguide/bedrock-runtime_example_bedrock-runtime_InvokeModel_AnthropicClaude_section.html

    log: logging.Logger = logging.getLogger("BedrockAnthropicChatCompletions")

    def __init__(self, aws_access_key: Optional[str] = None, aws_secret_key: Optional[str] = None, region_name: Optional[str] = "us-east-1",
                model_id: Optional[str] = "arn:aws:bedrock:us-east-1:275662791714:application-inference-profile/pnvyooa2q6ij") -> None:
        super().__init__(aws_access_key=aws_access_key, aws_secret_key=aws_secret_key, region_name=region_name)
        """
        Initialize the BedrockAnthropicChatCompletions class.
        
        Args:
            aws_access_key (str): The AWS access key.
            aws_secret_key (str): The AWS secret key.
            region_name (str): The AWS region name. Default is os.getenv("AWS_REGION").
            model_id (str): The model ID to use. Only accepts Anthropic Claude models.
            bedrock_client (BedrockClient): The BedrockClient instance.
        """
        self.model_id = model_id
        self.bedrock_client = self._get_bedrock_client()

    def predict(self, text: str, temperature: float = 0.3, max_tokens: int = 1024):
        """ Predict a chat completion based on the input text.

        Args:
            text (str): The input text to generate a chat completion for.
            temperature (float): Temperature for sampling (0-1). Default 0.3 for balanced creativity.
            max_tokens (int): Maximum tokens in response. Default 1024 for complex analysis.

        Returns:
            str: The chat completion generated by the model.
        """

        # Use provided values or defaults (more reasonable than 0.00001)
        temperature = min(max(temperature, 0.0), 1.0)  # Clamp between 0 and 1
        max_tokens = min(max(max_tokens, 100), 4096)  # Reasonable bounds

        # Format the request payload using the model's native structure.
        native_request = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": max_tokens,
            "temperature": temperature,
            "messages": [
                {
                    "role": "user",
                    "content": [{"type": "text", "text": text}],
                }
            ],
        }

        # Convert the native request to JSON.
        request = json.dumps(native_request)

        try:
            # Invoke the model with the request.
            response = self.bedrock_client.invoke_model(
                modelId=self.model_id, body=request)

        except (ClientError, Exception) as e:
            self.log.error(
                f"ERROR: Can't invoke '{self.model_id}'. Reason: {e}")
            exit(1)

        # Decode the response body.
        model_response = json.loads(response["body"].read())

        # Extract the response text.
        response_text = model_response["content"][0]["text"]

        return response_text
